version: '3.4'
services:
  api-gateway:
    container_name: Api-gateway
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restarts: always
  user-service:
    container_name: service-user
    build:
      context: ./userService
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - api-gateway
    restarts: always
  message-service:
    container_name: service-message
    build:
      context: ./messageService
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    depends_on:
      - api-gateway
    restarts: always
  admin-service:
    container_name: service-admin
    build: 
      context: ./adminService
      dockerfile: Dockerfile
    ports:
      - '8083:8083'
    depends_on:
      - api-gateway
    restarts: always
  rabbitmq-service:
    container_name: service-rabbitmq
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    depends_on:
      - api-gateway
    restarts: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin